apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wsi18f5ap-go
  janus-idp.io/tekton: wsi18f5ap-go
  backstage.io/kubernetes-id: wsi18f5ap-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wsi18f5ap-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
