apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wsi18f5ap-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wsi18f5ap-go 
  name: wsi18f5ap-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wsi18f5ap-go 
